### ISSUE TITLE
Anyone able to use this on Rails with Passenger?

### ISSUE THREAD

**Issue by sandipsubedi** [nguyenquangminh0711/ruby_jard#71]
**Is your feature request related to a problem? Please describe.**
I am just wondering if anyone was able to use this with on Rails with Passenger.

Because I am getting this error:

```
App 47027 output: Failed to attach. Jard could not detect a valid tty device.
App 47027 output: This bug occurs when the process Jard trying to access is a non-interactive environment  such as docker, daemon, sub-processes, etc.
App 47027 output: If you are confused, please submit an issue in https://github.com/nguyenquangminh0711/ruby_jard/issues.
```

**Describe the solution you'd like**
Jard working on Rails with Passenger.

**Describe alternatives you've considered**

**Additional context**
This gem looks great. I was having issues trying to use it on Rails with Passenger. I am just wondering if anyone was able to do that.

**Comment by nguyenquangminh0711** [comment]
@sandipsubedi Thanks for raising this. Unfortunately, recenty, there is no way to let Jard works with Passenger at the moment. The reason is that Passenger intentionally closes all stdin, stdout, stderr, and detaches the web server from current TTY, so, Jard has no idea which TTY to attach to. The situation is the same for docker, but docker and co allow us to enable TTY, while Passenger does not. In future, this can be done when Jard supports remote debugging. It's in the roadmap (https://rubyjard.org/docs/roadmap#milestone-integration), so stay tuned :muscle:

**Comment by sandipsubedi** [comment]
@nguyenquangminh0711  Thank you so much for the detailed response. I will be watching for updates in the future.
